/* eslint-disable global-require, quote-props */
const cards = {
  back: require('./back.png'),
  '1S': require('./1S.png'),
  '1H': require('./1H.png'),
  '1C': require('./1C.png'),
  '1D': require('./1D.png'),
  '2S': require('./2S.png'),
  '2H': require('./2H.png'),
  '2C': require('./2C.png'),
  '2D': require('./2D.png'),
  '3S': require('./3S.png'),
  '3H': require('./3H.png'),
  '3C': require('./3C.png'),
  '3D': require('./3D.png'),
  '4S': require('./4S.png'),
  '4H': require('./4H.png'),
  '4C': require('./4C.png'),
  '4D': require('./4D.png'),
  '5S': require('./5S.png'),
  '5H': require('./5H.png'),
  '5C': require('./5C.png'),
  '5D': require('./5D.png'),
  '6S': require('./6S.png'),
  '6H': require('./6H.png'),
  '6C': require('./6C.png'),
  '6D': require('./6D.png'),
  '7S': require('./7S.png'),
  '7H': require('./7H.png'),
  '7C': require('./7C.png'),
  '7D': require('./7D.png'),
  '8S': require('./8S.png'),
  '8H': require('./8H.png'),
  '8C': require('./8C.png'),
  '8D': require('./8D.png'),
  '9S': require('./9S.png'),
  '9H': require('./9H.png'),
  '9C': require('./9C.png'),
  '9D': require('./9D.png'),
  TS: require('./TS.png'),
  TH: require('./TH.png'),
  TC: require('./TC.png'),
  TD: require('./TD.png'),
  JS: require('./JS.png'),
  JH: require('./JH.png'),
  JC: require('./JC.png'),
  JD: require('./JD.png'),
  QS: require('./QS.png'),
  QH: require('./QH.png'),
  QC: require('./QC.png'),
  QD: require('./QD.png'),
  KS: require('./KS.png'),
  KH: require('./KH.png'),
  KC: require('./KC.png'),
  KD: require('./KD.png'),
};

export default cards;
