# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# See:
# https://github.com/marketplace/actions/vitest-coverage-report
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

name: Node.js CI

on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@bhoos'

    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ hashFiles('**/jut-engine/package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - run: npm install
      working-directory: ./jut-engine
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - run: npm run build
      working-directory: ./jut-engine

    - run: npm test -- --coverage run
      working-directory: ./jut-engine

    - name: Report Coverage
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        working-directory: ./jut-engine
